#!/bin/expect
set timeout {}
spawn {}
expect "Do you want to install PCCS now? (Y/N) :"
send "y\r"
expect "Do you want to configure PCCS now? (Y/N) :"
send "y\r"
expect -ex "Set HTTPS listening port \[8081] (1024-65535) :"
send "\r"
expect -ex "Set the PCCS service to accept local connections only? \[Y] (Y/N) :"
send "\r"
expect "Set your Intel PCS API key (Press ENTER to skip) :"
send "{}\r"
expect -ex "Choose caching fill method : \[LAZY] (LAZY/OFFLINE/REQ) :"
send "\r"
expect "Set PCCS server administrator password:"
send "{}\r"
expect "Re-enter administrator password:"
send "{}\r"
expect "Set PCCS server user password:"
send "{}\r"
expect "Re-enter user password:"
send "{}\r"
expect -ex "Do you want to generate insecure HTTPS key and cert for PCCS service? \[Y] (Y/N) :"
send "\r"
expect -ex "Country Name (2 letter code) \[XX]:"
send "\r"
expect -ex "State or Province Name (full name) \[]:"
send "\r"
expect -ex "Locality Name (eg, city) \[Default City]:"
send "\r"
expect -ex "Organization Name (eg, company) \[Default Company Ltd]:"
send "\r"
expect -ex "Organizational Unit Name (eg, section) \[]:"
send "\r"
expect -ex "Common Name (eg, your name or your server\'s hostname) \[]:"
send "\r"
expect -ex "Email Address \[]:"
send "\r"
expect -ex "A challenge password \[]:"
send "\r"
expect -ex "An optional company name \[]:"
send "\r"
expect eof

lassign [wait] pid spawnid os_error_flag value
