# Generated by Django 3.1.7 on 2021-03-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_id',
            field=models.IntegerField(unique=True),
        ),
    ]
