# Generated by Django 3.1.7 on 2021-03-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_remove_platform_platform_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsdes_id', models.TextField()),
                ('platform_name_short', models.TextField(blank=True)),
                ('title', models.TextField()),
                ('automation_owner', models.TextField(blank=True)),
                ('egs_blocked', models.TextField()),
                ('automation_script', models.TextField(blank=True)),
                ('non_automatable_reason', models.TextField(blank=True)),
                ('automation_comments', models.TextField(blank=True)),
                ('automation_remarks', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
            ],
        ),
    ]
