# Generated by Django 3.1.7 on 2021-03-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='automation_completion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='automation_eta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='automation_potential',
            field=models.TextField(blank=True),
        ),
    ]
