# Generated by Django 3.1.7 on 2021-03-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_auto_20210320_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='title',
        ),
    ]
