# Generated by Django 3.1.7 on 2021-03-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_remove_testcase_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='automation_applicable',
            field=models.TextField(blank=True),
        ),
    ]
