# Generated by Django 3.1.7 on 2021-03-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_testcase_automation_applicable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_name_short',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='hsdes_id',
            field=models.IntegerField(unique=True),
        ),
    ]
