# Generated by Django 3.1.7 on 2021-03-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_auto_20210320_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='hsdes_id',
            field=models.TextField(unique=True),
        ),
    ]
