# Generated by Django 3.1.7 on 2021-03-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_auto_20210320_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_id', models.TextField(unique=True)),
                ('platform', models.TextField()),
                ('domain', models.TextField(blank=True)),
                ('feature_group', models.TextField(blank=True)),
                ('database_source', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('milestone', models.TextField(blank=True)),
                ('bkc_candidate', models.TextField(blank=True)),
                ('automation_current', models.TextField(blank=True)),
                ('automation_potential', models.TextField(blank=True)),
                ('automation_eta', models.TextField(blank=True)),
                ('automation_completion', models.TextField(blank=True)),
                ('automation_deployed', models.TextField(blank=True)),
                ('script_path', models.TextField(blank=True)),
                ('automation_developer', models.TextField(blank=True)),
                ('operating_system', models.TextField(blank=True)),
                ('egs_blocked', models.TextField(blank=True)),
                ('automation_applicable', models.TextField(blank=True)),
                ('automation_category', models.TextField(blank=True)),
                ('automation_remarks', models.TextField(blank=True)),
                ('developer_comments', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
            ],
        ),
    ]
