# Generated by Django 3.1.7 on 2021-03-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_testcaseexcel_non_automatable_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BKCReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name_short', models.TextField()),
                ('report', models.TextField()),
                ('run_ids', models.TextField(blank=True)),
            ],
        ),
    ]
