# Generated by Django 3.1.7 on 2021-04-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0017_bkcreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_id', models.TextField()),
                ('platform', models.TextField()),
                ('title', models.TextField(blank=True)),
                ('platform_tc_category', models.TextField(blank=True)),
                ('execution_status', models.CharField(blank=True, max_length=250)),
                ('error_message', models.TextField(blank=True)),
                ('ticket_link', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestStepsExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_id', models.TextField()),
                ('platform', models.TextField(blank=True)),
                ('title', models.TextField()),
                ('step_number', models.TextField(blank=True)),
                ('step', models.TextField(blank=True)),
                ('expected_result', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('role', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='testcaseexcel',
            name='automation_block_category',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcaseexcel',
            name='automation_deployment_eta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcaseexcel',
            name='common_candidates',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcaseexcel',
            name='hw_config',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcaseexcel',
            name='is_new_tc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcaseexcel',
            name='is_deprecated',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcaseexcel',
            name='platform_tc_category',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcaseexcel',
            name='source_patch_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcaseexcel',
            name='temp_test_case_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='duration',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='report',
            name='result',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='report',
            name='startTime',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='report',
            name='stopTime',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='report',
            name='testPackageDisplayedName',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testcaseexcel',
            name='automation_potential',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
