# Generated by Django 3.2.4 on 2021-10-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0018_auto_20210426_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseexcel',
            name='phoenix_id',
            field=models.TextField(blank=True),
        ),
    ]
