#!/usr/bin/env python

from tkinter import *
from tkinter.messagebox import *

import utils


def soundwave():
    sw = Toplevel()
    sw.title('Soundwave Panel')
    sw['background'] = 'azure2'
    sw.width = 1190
    sw.height = 460
    sw.geometry(f'{sw.width}x{sw.height}')
    sw.resizable(False, False)

    attribute_frame = LabelFrame(sw, text='COM Attribute', pady=10, font=utils.TITLE_FONT, width=180, height=250)
    function_frame = LabelFrame(sw, text='Function Region', pady=10, font=utils.TITLE_FONT, width=210, height=250)
    jumper_frame = LabelFrame(sw, text='Jumper Setting', pady=10, font=utils.TITLE_FONT, width=465, height=235)
    voltage_frame = LabelFrame(sw, text='Voltage Detecting', pady=10, font=utils.TITLE_FONT, width=1170, height=170)

    attribute_frame.grid(row=0, column=0, padx=10, pady=10, sticky='nwes')
    attribute_frame.grid_propagate(False)
    function_frame.grid(row=0, column=1, padx=10, pady=10, sticky='nwes')
    function_frame.grid_propagate(False)
    jumper_frame.grid(row=0, column=2, padx=10, pady=10, sticky='nwes')
    jumper_frame.grid_propagate(False)
    voltage_frame.grid(row=1, column=0, columnspan=3, padx=10, pady=10, sticky='nwes')
    voltage_frame.grid_propagate(False)

    # com attribute
    port_label = Label(attribute_frame, text='Port', width=16, anchor='w', bg='lightblue')
    baud_label = Label(attribute_frame, text='Baud', anchor='w', bg='lightblue')
    p3v3_label = Label(attribute_frame, text='P3V3', anchor='w', bg='lightblue')
    p3v3aux_label = Label(attribute_frame, text='P3V3_AUX', anchor='w', bg='lightblue')

    port_entry = Entry(attribute_frame)
    baud_entry = Entry(attribute_frame)
    p3v3_entry = Entry(attribute_frame)
    p3v3aux_entry = Entry(attribute_frame)


    # todo: these attributes should be got from: sut.ini, marked as read-only
    # todo: the soundwave instance should be the same one as "System Monitor", so that it can work parallel
    # todo: each button in "Function Region" should not be independent when using com resource
    port_entry.insert(0, 'COM101')
    baud_entry.insert(0, '115200')
    p3v3_entry.insert(0, '2.8')
    p3v3aux_entry.insert(0, '0.8')

    port_label.grid(row=0, column=0, padx=5, pady=2, sticky='we')
    baud_label.grid(row=1, column=0, padx=5, pady=2, sticky='we')
    p3v3_label.grid(row=2, column=0, padx=5, pady=2, sticky='we')
    p3v3aux_label.grid(row=3, column=0, padx=5, pady=2, sticky='we')
    port_entry.grid(row=0, column=1, padx=5, pady=2, sticky='we')
    baud_entry.grid(row=1, column=1, padx=5, pady=2, sticky='we')
    p3v3_entry.grid(row=2, column=1, padx=5, pady=2, sticky='we')
    p3v3aux_entry.grid(row=3, column=1, padx=5, pady=2, sticky='we')


    # function region
    ac_on_button = Button(function_frame, text='AC ON', width=18).grid(row=0, column=0, padx=5, pady=2, sticky='we')
    ac_off_button = Button(function_frame, text='AC OFF', width=18).grid(row=0, column=1, padx=5, pady=2, sticky='we')
    dc_on_button = Button(function_frame, text='DC ON').grid(row=1, column=0, padx=5, pady=2, sticky='we')
    dc_off_button = Button(function_frame, text='DC OFF').grid(row=1, column=1, padx=5, pady=2, sticky='we')
    reset_button = Button(function_frame, text='RESET').grid(row=2, column=0, padx=5, pady=2, sticky='we')
    usb_open_button = Button(function_frame, text='USB -> Open').grid(row=2, column=1, padx=5, pady=2, sticky='we')
    usb_host_button = Button(function_frame, text='USB -> Host').grid(row=3, column=0, padx=5, pady=2, sticky='we')
    usb_sut_button = Button(function_frame, text='USB -> SUT').grid(row=3, column=1, padx=5, pady=2, sticky='we')
    sut_power_button = Button(function_frame, text='SUT Power Detecting').grid(row=4, column=0, padx=5, pady=2, sticky='we')
    sut_power_entry = Entry(function_frame, state='disabled').grid(row=4, column=1, padx=5, pady=2, sticky='we')
    sw_fw_button = Button(function_frame, text='SW FW Checking').grid(row=5, column=0, padx=5, pady=2, sticky='we')
    sw_fw_entry = Entry(function_frame, state='disabled').grid(row=5, column=1, padx=5, pady=2, sticky='we')

    # jumper setting
    connect_12_frame = Frame(jumper_frame, bg='azure2')
    connect_23_frame = Frame(jumper_frame, bg='azure2')

    connect_12_frame.grid(row=0, column=0, padx=5)
    connect_23_frame.grid(row=0, column=1, padx=5)

    connect_12_label = Label(connect_12_frame, text='Connect 1-2', bg='lightyellow', font=('Times', '10', 'bold italic')).grid(row=0, column=0, columnspan=2, padx=5, pady=4, sticky='we')
    connect_23_label = Label(connect_23_frame, text='Connect 2-3', bg='lightyellow', font=('Times', '10', 'bold italic')).grid(row=0, column=0, columnspan=2, padx=5, pady=4, sticky='we')

    connect_12_dpout_1 = Button(connect_12_frame, text='DP_OUT_1', width=16).grid(row=1, column=0, padx=5, pady=2, sticky='we')
    connect_12_dpout_2 = Button(connect_12_frame, text='DP_OUT_2', width=16).grid(row=1, column=1, padx=5, pady=2, sticky='we')
    connect_12_dpout_3 = Button(connect_12_frame, text='DP_OUT_3').grid(row=2, column=0, padx=5, pady=2, sticky='we')
    connect_12_dpout_4 = Button(connect_12_frame, text='DP_OUT_4').grid(row=2, column=1, padx=5, pady=2, sticky='we')
    connect_12_dpout_5 = Button(connect_12_frame, text='DP_OUT_5').grid(row=3, column=0, padx=5, pady=2, sticky='we')
    connect_12_dpout_6 = Button(connect_12_frame, text='DP_OUT_6').grid(row=3, column=1, padx=5, pady=2, sticky='we')
    connect_12_dpout_7 = Button(connect_12_frame, text='DP_OUT_7').grid(row=4, column=0, padx=5, pady=2, sticky='we')
    connect_12_dpout_8 = Button(connect_12_frame, text='DP_OUT_8').grid(row=4, column=1, padx=5, pady=2, sticky='we')
    connect_12_dpout_9 = Button(connect_12_frame, text='DP_OUT_9').grid(row=5, column=0, padx=5, pady=2, sticky='we')
    connect_12_dpout_10 = Button(connect_12_frame, text='DP_OUT_10').grid(row=5, column=1, padx=5, pady=2, sticky='we')
    connect_12_dpout_11 = Button(connect_12_frame, text='DP_OUT_11').grid(row=6, column=0, padx=5, pady=2, sticky='we')
    connect_12_dpout_12 = Button(connect_12_frame, text='DP_OUT_12').grid(row=6, column=1, padx=5, pady=2, sticky='we')

    connect_23_dpout_1 = Button(connect_23_frame, text='DP_OUT_1', width=16).grid(row=1, column=0, padx=5, pady=2, sticky='we')
    connect_23_dpout_2 = Button(connect_23_frame, text='DP_OUT_2', width=16).grid(row=1, column=1, padx=5, pady=2, sticky='we')
    connect_23_dpout_3 = Button(connect_23_frame, text='DP_OUT_3').grid(row=2, column=0, padx=5, pady=2, sticky='we')
    connect_23_dpout_4 = Button(connect_23_frame, text='DP_OUT_4').grid(row=2, column=1, padx=5, pady=2, sticky='we')
    connect_23_dpout_5 = Button(connect_23_frame, text='DP_OUT_5').grid(row=3, column=0, padx=5, pady=2, sticky='we')
    connect_23_dpout_6 = Button(connect_23_frame, text='DP_OUT_6').grid(row=3, column=1, padx=5, pady=2, sticky='we')
    connect_23_dpout_7 = Button(connect_23_frame, text='DP_OUT_7').grid(row=4, column=0, padx=5, pady=2, sticky='we')
    connect_23_dpout_8 = Button(connect_23_frame, text='DP_OUT_8').grid(row=4, column=1, padx=5, pady=2, sticky='we')
    connect_23_dpout_9 = Button(connect_23_frame, text='DP_OUT_9').grid(row=5, column=0, padx=5, pady=2, sticky='we')
    connect_23_dpout_10 = Button(connect_23_frame, text='DP_OUT_10').grid(row=5, column=1, padx=5, pady=2, sticky='we')
    connect_23_dpout_11 = Button(connect_23_frame, text='DP_OUT_11').grid(row=6, column=0, padx=5, pady=2, sticky='we')
    connect_23_dpout_12 = Button(connect_23_frame, text='DP_OUT_12').grid(row=6, column=1, padx=5, pady=2, sticky='we')


    # voltage setting
    ad_in_1_label = Label(voltage_frame, text='AD_IN_1', width=8, anchor='w').grid(row=0, column=0, padx=5, pady=2)
    ad_in_2_label = Label(voltage_frame, text='AD_IN_2', width=8, anchor='w').grid(row=0, column=2, padx=5, pady=2)
    ad_in_3_label = Label(voltage_frame, text='AD_IN_3', width=8, anchor='w').grid(row=0, column=4, padx=5, pady=2)
    ad_in_4_label = Label(voltage_frame, text='AD_IN_4', width=8, anchor='w').grid(row=0, column=6, padx=5, pady=2)
    ad_in_5_label = Label(voltage_frame, text='AD_IN_5', width=8, anchor='w').grid(row=0, column=8, padx=5, pady=2)
    ad_in_6_label = Label(voltage_frame, text='AD_IN_6', width=8, anchor='w').grid(row=0, column=10, padx=5, pady=2)
    ad_in_7_label = Label(voltage_frame, text='AD_IN_7', width=8, anchor='w').grid(row=0, column=12, padx=5, pady=2)
    ad_in_8_label = Label(voltage_frame, text='AD_IN_8', width=8, anchor='w').grid(row=0, column=14, padx=5, pady=2)
    ad_in_9_label = Label(voltage_frame, text='AD_IN_9', width=8, anchor='w').grid(row=1, column=0, padx=5, pady=2)
    ad_in_10_label = Label(voltage_frame, text='AD_IN_10', width=8, anchor='w').grid(row=1, column=2, padx=5, pady=2)
    ad_in_11_label = Label(voltage_frame, text='AD_IN_11', width=8, anchor='w').grid(row=1, column=4, padx=5, pady=2)
    ad_in_12_label = Label(voltage_frame, text='AD_IN_12', width=8, anchor='w').grid(row=1, column=6, padx=5, pady=2)
    ad_in_13_label = Label(voltage_frame, text='AD_IN_13', width=8, anchor='w').grid(row=1, column=8, padx=5, pady=2)
    ad_in_14_label = Label(voltage_frame, text='AD_IN_14', width=8, anchor='w').grid(row=1, column=10, padx=5, pady=2)
    ad_in_15_label = Label(voltage_frame, text='AD_IN_15', width=8, anchor='w').grid(row=1, column=12, padx=5, pady=2)
    ad_in_16_label = Label(voltage_frame, text='AD_IN_16', width=8, anchor='w').grid(row=1, column=14, padx=5, pady=2)
    ad_in_17_label = Label(voltage_frame, text='AD_IN_17', width=8, anchor='w').grid(row=2, column=0, padx=5, pady=2)
    ad_in_18_label = Label(voltage_frame, text='AD_IN_18', width=8, anchor='w').grid(row=2, column=2, padx=5, pady=2)
    ad_in_19_label = Label(voltage_frame, text='AD_IN_19', width=8, anchor='w').grid(row=2, column=4, padx=5, pady=2)
    ad_in_20_label = Label(voltage_frame, text='AD_IN_20', width=8, anchor='w').grid(row=2, column=6, padx=5, pady=2)
    ad_in_21_label = Label(voltage_frame, text='AD_IN_21', width=8, anchor='w').grid(row=2, column=8, padx=5, pady=2)
    ad_in_22_label = Label(voltage_frame, text='AD_IN_22', width=8, anchor='w').grid(row=2, column=10, padx=5, pady=2)
    ad_in_23_label = Label(voltage_frame, text='AD_IN_23', width=8, anchor='w').grid(row=2, column=12, padx=5, pady=2)
    ad_in_24_label = Label(voltage_frame, text='AD_IN_24', width=8, anchor='w').grid(row=2, column=14, padx=5, pady=2)
    ad_in_25_label = Label(voltage_frame, text='AD_IN_25', width=8, anchor='w').grid(row=3, column=0, padx=5, pady=2)
    ad_in_26_label = Label(voltage_frame, text='AD_IN_26', width=8, anchor='w').grid(row=3, column=2, padx=5, pady=2)
    ad_in_27_label = Label(voltage_frame, text='AD_IN_27', width=8, anchor='w').grid(row=3, column=4, padx=5, pady=2)
    ad_in_28_label = Label(voltage_frame, text='AD_IN_28', width=8, anchor='w').grid(row=3, column=6, padx=5, pady=2)
    ad_in_29_label = Label(voltage_frame, text='AD_IN_29', width=8, anchor='w').grid(row=3, column=8, padx=5, pady=2)
    ad_in_30_label = Label(voltage_frame, text='AD_IN_30', width=8, anchor='w').grid(row=3, column=10, padx=5, pady=2)
    ad_in_31_label = Label(voltage_frame, text='AD_IN_31', width=8, anchor='w').grid(row=3, column=12, padx=5, pady=2)
    ad_in_32_label = Label(voltage_frame, text='AD_IN_32', width=8, anchor='w').grid(row=3, column=14, padx=5, pady=2)
    ad_in_33_label = Label(voltage_frame, text='AD_IN_33', width=8, anchor='w').grid(row=4, column=0, padx=5, pady=2)
    ad_in_34_label = Label(voltage_frame, text='AD_IN_34', width=8, anchor='w').grid(row=4, column=2, padx=5, pady=2)
    ad_in_35_label = Label(voltage_frame, text='AD_IN_35', width=8, anchor='w').grid(row=4, column=4, padx=5, pady=2)
    ad_in_36_label = Label(voltage_frame, text='AD_IN_36', width=8, anchor='w').grid(row=4, column=6, padx=5, pady=2)
    ad_in_37_label = Label(voltage_frame, text='AD_IN_37', width=8, anchor='w').grid(row=4, column=8, padx=5, pady=2)
    ad_in_38_label = Label(voltage_frame, text='AD_IN_38', width=8, anchor='w').grid(row=4, column=10, padx=5, pady=2)
    ad_in_39_label = Label(voltage_frame, text='AD_IN_39', width=8, anchor='w').grid(row=4, column=12, padx=5, pady=2)
    ad_in_40_label = Label(voltage_frame, text='AD_IN_40', width=8, anchor='w').grid(row=4, column=14, padx=5, pady=2)

    ad_in_1_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=0, column=1, padx=5, pady=2)
    ad_in_2_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=0, column=3, padx=5, pady=2)
    ad_in_3_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=0, column=5, padx=5, pady=2)
    ad_in_4_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=0, column=7, padx=5, pady=2)
    ad_in_5_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=0, column=9, padx=5, pady=2)
    ad_in_6_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=0, column=11, padx=5, pady=2)
    ad_in_7_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=0, column=13, padx=5, pady=2)
    ad_in_8_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=0, column=15, padx=5, pady=2)
    ad_in_9_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=1, column=1, padx=5, pady=2)
    ad_in_10_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=1, column=3, padx=5, pady=2)
    ad_in_11_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=1, column=5, padx=5, pady=2)
    ad_in_12_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=1, column=7, padx=5, pady=2)
    ad_in_13_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=1, column=9, padx=5, pady=2)
    ad_in_14_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=1, column=11, padx=5, pady=2)
    ad_in_15_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=1, column=13, padx=5, pady=2)
    ad_in_16_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=1, column=15, padx=5, pady=2)
    ad_in_17_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=2, column=1, padx=5, pady=2)
    ad_in_18_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=2, column=3, padx=5, pady=2)
    ad_in_19_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=2, column=5, padx=5, pady=2)
    ad_in_20_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=2, column=7, padx=5, pady=2)
    ad_in_21_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=2, column=9, padx=5, pady=2)
    ad_in_22_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=2, column=11, padx=5, pady=2)
    ad_in_23_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=2, column=13, padx=5, pady=2)
    ad_in_24_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=2, column=15, padx=5, pady=2)
    ad_in_25_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=3, column=1, padx=5, pady=2)
    ad_in_26_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=3, column=3, padx=5, pady=2)
    ad_in_27_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=3, column=5, padx=5, pady=2)
    ad_in_28_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=3, column=7, padx=5, pady=2)
    ad_in_29_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=3, column=9, padx=5, pady=2)
    ad_in_30_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=3, column=11, padx=5, pady=2)
    ad_in_31_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=3, column=13, padx=5, pady=2)
    ad_in_32_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=3, column=15, padx=5, pady=2)
    ad_in_33_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=4, column=1, padx=5, pady=2)
    ad_in_34_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=4, column=3, padx=5, pady=2)
    ad_in_35_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=4, column=5, padx=5, pady=2)
    ad_in_36_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=4, column=7, padx=5, pady=2)
    ad_in_37_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=4, column=9, padx=5, pady=2)
    ad_in_38_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=4, column=11, padx=5, pady=2)
    ad_in_39_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=4, column=13, padx=5, pady=2)
    ad_in_40_entry = Entry(voltage_frame, width=8, state='disabled').grid(row=4, column=15, padx=5, pady=2)

    ad_in_start_button = Button(voltage_frame, text='Start').grid(row=0, column=16, rowspan=5, padx=5, sticky='ns')
    ad_in_stop_button = Button(voltage_frame, text='Stop').grid(row=0, column=17, rowspan=5, sticky='ns')
